### ISSUE TITLE
Issue with Ambient Mode

### ISSUE THREAD

**Issue by Blarnix** [therealFoxster/DontEatMyContent#14]
Hi,

Recently found that a YouTube update internally made it so that ambient mode shows on the sides of videos that are widescreen, which looks fine wit DontEatMyContent disabled, but with it enabled, it causes this effect:
![image](https://github.com/therealFoxster/DontEatMyContent/assets/61402697/ce0f686f-fcb3-4aa5-921c-265bc3b1a2c9)
![image](https://github.com/therealFoxster/DontEatMyContent/assets/61402697/6ed95d1e-4541-4f0c-8c04-e575675f9f33)

On the tops and bottoms, there are black bars that are not the colors of the ambient mode as it seems. Maybe a feature to enable or disable the ambient mode behavior during playback would help to resolve the issue? I personally am not sure if it'd look better with ambient mode on the tops and bottoms or not, instead of all black around.

Thanks.

**Comment by therealFoxster** [comment]
Thanks for reporting! I think 71ff14e should fix it. I'm gonna build a new release soon if you're using the .DEB file. Otherwise, you can wait till your tweaked YouTube app (uYouPlus or otherwise) gets updated.

**Comment by Blarnix** [comment]
Awesome, I'll follow up with the maintainer of uYouPlus+ to get it added to the next release. Thanks for being so on top of this.

**Comment by C7XL** [comment]
![IMG_0246](https://github.com/therealFoxster/DontEatMyContent/assets/11635731/1ea912c1-df9a-4a5a-9452-7210c60b37d8)

**Comment by therealFoxster** [comment]
Yeah I’m working on an option to for you to toggle between ambient mode and just plain black bars
