### ISSUE TITLE
Issue with Fullscreen Zoom

### ISSUE THREAD

**Issue by Blarnix** [therealFoxster/DontEatMyContent#15]
Hi again,

Just wanted to also put this here so you were aware, there is a weird jittery/glitchy behavior when using DontEatMyContent in fullscreen. 

https://github.com/therealFoxster/DontEatMyContent/assets/61402697/e3a19b8e-5dee-4ce9-bc5e-4186752f6878

It's very possible that this is an incompatibility with UYouPlus++'s "Disable Pinch to Zoom" function, as when disabled, the behavior corrects itself.

![image](https://github.com/therealFoxster/DontEatMyContent/assets/61402697/2a417cb1-f5b4-40e7-9458-77f406050bc9)

Not sure if there's anything on your side to fix, but just figured I'd let you know of it. I'll also report this on their repo and see what they have to say.
Thanks again.

**Comment by therealFoxster** [comment]
Thanks! I think they nuked the pinch recognizer which I'm using to deactivate the constraints when you pinch to zoom. a08f9d9 should fix this.

**Comment by Blarnix** [comment]
Alright, thanks.
