### ISSUE TITLE
Dynamic Island cutting into video

### ISSUE THREAD

**Issue by wongwengtim** [therealFoxster/DontEatMyContent#17]
![IMG_0434](https://github.com/therealFoxster/DontEatMyContent/assets/32707423/e530357c-1ed3-4baa-ba95-3ae34ac5497f)
![IMG_0437](https://github.com/therealFoxster/DontEatMyContent/assets/32707423/27250718-6ac2-45cc-8e9f-a90a813597f1)

Version: 1.1.0
Device: iPhone 15
Video: https://youtu.be/xminXUvDi4g

**Comment by therealFoxster** [comment]
Thanks for reporting! bd4e954 should address this.
