### ISSUE TITLE
Ability to Hide Channel Watermark

### ISSUE THREAD

**Issue by arichornlover** [therealFoxster/DontEatMyContent#21]
Hello theRealFoxster! Was wondering if you want to add an option that hides the channel watermark. This can be great for DontEatMyContent if the watermark can be an annoyance and I already know the tweaks from uYouPlus/uYouEnhanced have that option but sadly they no longer work on the latest YouTube version because of the removal of `YTAnnotationsViewController` 
and I did try to use stuff like `YTIElementRenderer` but when I did that it broke the tapping functionality in the video player if a video had a watermark. But then I tried `YTMainAppVideoPlayerOverlayView` and it worked but if you went into a different app and hop back on YouTube it will reappear. So what are your thoughts on this option?

```
%hook YTAnnotationsViewController // Deprecated - YouTube v18.30+
- (void)loadFeaturedChannelWatermark {
    if (IsEnabled(@"hideChannelWatermark_enabled")) {}
    else { return %orig; }
}
%end
```

**Comment by therealFoxster** [comment]
Thanks for the suggestion! It's a neat feature but I probably won't be adding it to DontEatMyContent since it doesn't have anything to do with the notch/Dynamic Island
