### ISSUE TITLE
Opening YouTube's settings panel crashes the Application

### ISSUE THREAD

**Issue by eyeslow** [therealFoxster/DontEatMyContent#24]
YouTube changed the behaviour of their settings panel in 19.03.2 which leads to crashes when using incompatible tweaks. Some developers (mainly user:poomsmart) published their way of fixing the issue on their repositories, maybe it helps to look into it.

Thanks in advance, have a good one!

**Comment by therealFoxster** [comment]
I have addressed this in d6816e2. Thanks for reporting!
