### ISSUE TITLE
[v1.1.5] Home page videos turn black and become unclickable

### ISSUE THREAD

**Issue by gierigetjapper026** [therealFoxster/DontEatMyContent#33]
When i scroll on the homepage sometimes i cant see and click videos it just turn black

**Comment by therealFoxster** [comment]
Likely an issue with uYou. Turn off uYou adblocker (uYou > Settings > Other Settings > Remove YouTube Ads).

**Comment by gierigetjapper026** [comment]
Yes that was the isue thx alot also for the fast respons😁💪🏽

Op ma 10 jun 2024 om 18:24 schreef Huy ***@***.***>
