### ISSUE TITLE
Rootless support?

### ISSUE THREAD

**Issue by CySxL** [therealFoxster/DontEatMyContent#38]
Would there be arm64(rootless) and arm64e(roothide) builds provided also?

**Comment by therealFoxster** [comment]
I can look into that. No promises tho

**Comment by CySxL** [comment]
@therealFoxster Thanks!! Looking foreward to it!

**Comment by therealFoxster** [comment]
I added a rootless build for the latest release. I most likely won't do the same for roothide until Theos officially supports it.

**Comment by CySxL** [comment]
Saw it and installed it at the first minute haha, so far so good!! Thanks a lot mate!


Oh yeah dw about roothide, it's still in its beta period so yeah understandable : D
