### ISSUE TITLE
Dynamic Island still cutting into video

### ISSUE THREAD

**Issue by BatSmacker84** [therealFoxster/DontEatMyContent#5]
#4 already exists, but no information was given about what that issue actually was and then it was closed. 

On the iPhone 14 Pro the Dynamic Island still cuts into the video. I have sideloaded the tweak with uYouPlus, the provided AltStore IPA, and injecting it manually with no success.

**Comment by therealFoxster** [comment]
Can you try installing [this version](https://github.com/therealFoxster/DontEatMyContent/releases/tag/v1.0.0-7%2Bdebug) and share screenshots of how it looks on your end? A screen recording of you pinching in and out would be even better. It should look something like this: ![IMG_2170](https://user-images.githubusercontent.com/77606385/193708397-6ed3f905-3fce-469d-914c-9aacabeae432.PNG)

**Comment by BatSmacker84** [comment]
For some reason it works in this IPA, but not the others. I assume that some changes were made between the v1.0.0 release and the version used here. 

The dynamic island is hidden from screen recording and screen shots, but it is no longer interfering. You can see the blue edges cropping in the video to avoid it. 

https://user-images.githubusercontent.com/94207271/193940613-b8a25fc5-05c6-480e-9c78-277dce476ae8.mov

**Comment by therealFoxster** [comment]
That's very strange and interesting, as all I really did was setting background colors for the views (the code was already there too just commented out). I might have released an older version of the tweak as [v1.0.0](https://github.com/therealFoxster/DontEatMyContent/releases/tag/v1.0.0), hence why it wasn't working properly with the Dynamic Island, though I'm not entirely sure. 

Regardless, I removed the views' background colors, recompiled and released the tweak under [v1.0.1](https://github.com/therealFoxster/DontEatMyContent/releases/tag/v1.0.1). No new code/functionality but hopefully this version fixes Dynamic Island support if I released the wrong thing for v1.0.0. 

Please let me know if you're still having issues!

## Links
* https://github.com/therealFoxster/DontEatMyContent/releases/tag/v1.0.1
* https://therealfoxster.github.io/altsource/app.html?id=youtube

**Comment by BatSmacker84** [comment]
Whatever the issue was, the tweak works perfectly now. I can inject it into both the IPA provided before and uYouPlus and it works. 

Thanks for the help!

**Comment by therealFoxster** [comment]
Yes. Is it still not working for you?
