### ISSUE TITLE
Crashing with YouTube 18.19.1 (sideloaded)

### ISSUE THREAD

**Issue by eyeslow** [therealFoxster/DontEatMyContent#7]
I've tried to add the latest release (1.0.8) to YouTube 18.19.1 with Sideloadly which leads to instant app crashes during launch.

For context, it's not YouTube vanilla as there are some other tweaks injected as well, see the list of other tweaks [here on AppDB.](https://appdb.to/app/cydia/1900001070)

**Comment by therealFoxster** [comment]
Would you mind sharing the crash log?

**Comment by therealFoxster** [comment]
I think I might have an idea of what's causing this. I changed the required architecture from arm64e and min. firmware to 14.1. If you were testing it on an arm64 device or one that's on iOS < 14.1, the tweak will crash. That was very careless by me and I'll most likely have to revert these changes since the tweak is also used in uYouPlus which supports iOS >= 14.0 and arm64 devices so the tweak might cause a crash for some users.

**Comment by eyeslow** [comment]
> I think I might have an idea of what's causing this. I changed the required architecture from arm64e and min. firmware to 14.1. If you were testing it on an arm64 device or one that's on iOS < 14.1, the tweak will crash. That was very careless by me and I'll most likely have to revert these changes since the tweak is also used in uYouPlus which supports iOS >= 14.0 and arm64 devices and might cause a crash for some users.

I was testing it on a jailbroken 6s (arm64) on 15.7.1 and experienced crashing, therefore I did not install it to my main device, a non-jailbroken 13 Pro Max (arm64e) on 16.5... Just tested the new release (1.0.9) on the 6s AND the 13 Pro Max and now its working flawlessly, not causing a crash and even showing up in YouTube's settings panel (even though its not actually needed on neither of the two devices)... 

![IMG_0007](https://github.com/therealFoxster/DontEatMyContent/assets/49617557/79eec44c-8ed3-4829-804c-ace901264bf0)


Thanks for your quick responses and bugfixes!
Cheers!

**Comment by therealFoxster** [comment]
Ah that's what I figured. Since v1.0.8 only supports arm64e devices, the tweak crashes on your 6s (arm64). I'm glad it's not doing so anymore. Enjoy!
